// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKzx4XW39z9MzrcbslSyu9b8_RKVS6Osc',
    appId: '1:355935679190:web:a63f7f44d2f3a8f4ca0f77',
    messagingSenderId: '355935679190',
    projectId: 'atelier4-m-jabbar-iir5g3',
    authDomain: 'atelier4-m-jabbar-iir5g3.firebaseapp.com',
    storageBucket: 'atelier4-m-jabbar-iir5g3.appspot.com',
    measurementId: 'G-051RQJ7Q58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTDj836UQYEqIwmxcbEUdhz1GvPH5Tq5U',
    appId: '1:355935679190:android:4d7a8639e190e51dca0f77',
    messagingSenderId: '355935679190',
    projectId: 'atelier4-m-jabbar-iir5g3',
    storageBucket: 'atelier4-m-jabbar-iir5g3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEneyT8Ggv2kRfjK1vCmSJoHGDaMb_Nfc',
    appId: '1:355935679190:ios:ed56629e42f93611ca0f77',
    messagingSenderId: '355935679190',
    projectId: 'atelier4-m-jabbar-iir5g3',
    storageBucket: 'atelier4-m-jabbar-iir5g3.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEneyT8Ggv2kRfjK1vCmSJoHGDaMb_Nfc',
    appId: '1:355935679190:ios:ed56629e42f93611ca0f77',
    messagingSenderId: '355935679190',
    projectId: 'atelier4-m-jabbar-iir5g3',
    storageBucket: 'atelier4-m-jabbar-iir5g3.appspot.com',
    iosBundleId: 'com.example.app1',
  );
}
